name: Manual Download and Upload Images

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Run download script
        run: |
          chmod +x download_images.sh
          ./download_images.sh

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: manual-release-${{ github.run_id }}
          release_name: Manual Release ${{ github.run_id }}
          draft: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloaded_images.zip
          asset_name: downloaded_images.zip
          asset_content_type: application/zip
          token: ${{ secrets.RELEASE_TOKEN }}
