name: Flashscore Image Scraper

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  scrape-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run the scraper
      run: python flashscore.py
      
    - name: Create summary file
      run: |
        mkdir -p ./output
        echo "# Flashscore Image Scraper Summary" > ./output/summary.md
        echo "" >> ./output/summary.md
        echo "Date: $(date +'%Y-%m-%d %H:%M:%S UTC')" >> ./output/summary.md
        echo "" >> ./output/summary.md
        echo "Images scraped from Flashscore football tournaments." >> ./output/summary.md
        echo "" >> ./output/summary.md
        echo "## Regions" >> ./output/summary.md
        ls -la ./output | grep "^d" | awk '{print "- " $9}' >> ./output/summary.md
      
    - name: Archive output as ZIP
      run: |
        sudo apt-get install -y zip
        cd output
        zip -r ../flashscore-images.zip .
        cd ..
      
    - name: Set date for release tag
      id: date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: flashscore-${{ steps.date.outputs.TODAY }}
        name: Flashscore Images ${{ steps.date.outputs.TODAY }}
        body_path: ./output/summary.md
        files: flashscore-images.zip
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
